# Generated by Django 4.0.1 on 2022-04-18 06:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_text', ckeditor.fields.RichTextField()),
                ('Terms', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
