# Generated by Django 4.0.1 on 2022-04-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_about_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_text',
            field=models.TextField(max_length=2000),
        ),
    ]
