# Generated by Django 4.0.1 on 2022-04-18 07:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_about_about_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
