# Generated by Django 4.0.1 on 2022-04-05 17:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=1000)),
                ('location', models.CharField(max_length=200)),
                ('duration', models.IntegerField()),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('package_img', models.ImageField(blank=True, upload_to='photos/')),
                ('max_size', models.IntegerField()),
                ('transport', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('activities', models.CharField(choices=[('Tour', 'Tour'), ('Trekking', 'Trekking'), ('Sight seeing', 'Sight seeing'), ('Jungle safari', 'Jungle safari'), ('mountaineering', 'mountaineering')], max_length=200)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='booking_tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=200)),
                ('lastname', models.CharField(default='', max_length=200)),
                ('persons', models.CharField(default='', max_length=200)),
                ('country', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(default='', max_length=200)),
                ('mobile', models.CharField(default='', max_length=18)),
                ('price', models.IntegerField(default='0')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('arrival_date', models.DateField(default=django.utils.timezone.now)),
                ('departure_date', models.DateField(default=django.utils.timezone.now)),
                ('comments', models.TextField(blank=True, max_length=1000, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('destination', models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='packages.package')),
            ],
        ),
    ]
