# Generated by Django 4.0.1 on 2022-02-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=500)),
                ('location', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='photos/% Y/% m/%d/')),
                ('max_size', models.IntegerField()),
                ('transport', models.BooleanField()),
                ('is_featured', models.BooleanField()),
                ('activities', models.CharField(choices=[('Tour', 'Tour'), ('Trekking', 'Trekking'), ('Sight seeing', 'Sight seeing'), ('Jungle safari', 'Jungle safari'), ('mountaineering', 'mountaineering')], max_length=200)),
            ],
        ),
    ]
