# Generated by Django 4.0.1 on 2022-04-05 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_tour',
            name='destination',
            field=models.OneToOneField(default='{{package.destination}}', null=True, on_delete=django.db.models.deletion.CASCADE, to='packages.package'),
        ),
    ]
