# Generated by Django 4.0.1 on 2022-04-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_alter_booking_tour_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_tour',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='package',
            name='id',
        ),
        migrations.AddField(
            model_name='booking_tour',
            name='trip_name',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='destination',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
