# Generated by Django 4.0.1 on 2022-04-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_remove_booking_tour_destination_remove_package_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('trip', models.CharField(default='', max_length=200, null=True)),
                ('price', models.IntegerField(default='0')),
                ('persons', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
