# Generated by Django 4.0.1 on 2022-02-19 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0010_alter_package_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='photo',
            new_name='package_img',
        ),
    ]
