# Generated by Django 4.0.1 on 2022-02-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0012_alter_package_package_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package_img',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
