# Generated by Django 4.0.1 on 2022-02-20 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0013_alter_package_package_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
