# Generated by Django 4.0.1 on 2022-02-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0014_package_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package_img',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
