# Generated by Django 4.0.1 on 2022-03-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0015_alter_package_package_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
